/**
 * @file variant_io.h
 * @author askn (K.Sato) multix.jp
 * @brief
 * @version 0.1
 * @date 2024-05-12
 *
 * @copyright Copyright (c) 2024 askn37 at github.com
 *
 */
// MIT License : https://askn37.github.io/LICENSE.html

#include <avr/io.h>
#define AVR_MEGAAVR_LIKE_MODERNAVR

#define SLEEP_MODE_ADC      SLEEP_MODE_STANDBY

/* RS485 Mode internal transmitter select */
#define USART_RS485_EXT_gc  (0x01<<0)
#define USART_RS485_INT_gc  (0x02<<0)

#define USART_RS485_0_bm    (1<<0)  /* RS485 Mode internal transmitter bit 0 mask. */
#define USART_RS485_0_bp    0       /* RS485 Mode internal transmitter bit 0 position. */
#define USART_RS485_1_bm    (1<<1)  /* RS485 Mode internal transmitter bit 1 mask. */
#define USART_RS485_1_bp    1       /* RS485 Mode internal transmitter bit 1 position. */

/* C Language Only */
#if !defined (__ASSEMBLER__)

#ifdef ENABLE_RBC
/* Backward compatibility not recommended */

/* Channel generator select */
#define EVSYS_CHANNEL0_OFF_gc EVSYS_CHANNEL_OFF_gc
#define EVSYS_CHANNEL1_OFF_gc EVSYS_CHANNEL_OFF_gc
#define EVSYS_CHANNEL2_OFF_gc EVSYS_CHANNEL_OFF_gc
#define EVSYS_CHANNEL3_OFF_gc EVSYS_CHANNEL_OFF_gc
#define EVSYS_CHANNEL4_OFF_gc EVSYS_CHANNEL_OFF_gc
#define EVSYS_CHANNEL5_OFF_gc EVSYS_CHANNEL_OFF_gc
#define EVSYS_CHANNEL0_RTC_OVF_gc EVSYS_CHANNEL_RTC_OVF_gc
#define EVSYS_CHANNEL1_RTC_OVF_gc EVSYS_CHANNEL_RTC_OVF_gc
#define EVSYS_CHANNEL2_RTC_OVF_gc EVSYS_CHANNEL_RTC_OVF_gc
#define EVSYS_CHANNEL3_RTC_OVF_gc EVSYS_CHANNEL_RTC_OVF_gc
#define EVSYS_CHANNEL4_RTC_OVF_gc EVSYS_CHANNEL_RTC_OVF_gc
#define EVSYS_CHANNEL5_RTC_OVF_gc EVSYS_CHANNEL_RTC_OVF_gc
#define EVSYS_CHANNEL0_RTC_CMP_gc EVSYS_CHANNEL_RTC_CMP_gc
#define EVSYS_CHANNEL1_RTC_CMP_gc EVSYS_CHANNEL_RTC_CMP_gc
#define EVSYS_CHANNEL2_RTC_CMP_gc EVSYS_CHANNEL_RTC_CMP_gc
#define EVSYS_CHANNEL3_RTC_CMP_gc EVSYS_CHANNEL_RTC_CMP_gc
#define EVSYS_CHANNEL4_RTC_CMP_gc EVSYS_CHANNEL_RTC_CMP_gc
#define EVSYS_CHANNEL5_RTC_CMP_gc EVSYS_CHANNEL_RTC_CMP_gc
#define EVSYS_CHANNEL0_CCL_LUT0_gc EVSYS_CHANNEL_CCL_LUT0_gc
#define EVSYS_CHANNEL1_CCL_LUT0_gc EVSYS_CHANNEL_CCL_LUT0_gc
#define EVSYS_CHANNEL2_CCL_LUT0_gc EVSYS_CHANNEL_CCL_LUT0_gc
#define EVSYS_CHANNEL3_CCL_LUT0_gc EVSYS_CHANNEL_CCL_LUT0_gc
#define EVSYS_CHANNEL4_CCL_LUT0_gc EVSYS_CHANNEL_CCL_LUT0_gc
#define EVSYS_CHANNEL5_CCL_LUT0_gc EVSYS_CHANNEL_CCL_LUT0_gc
#define EVSYS_CHANNEL0_CCL_LUT1_gc EVSYS_CHANNEL_CCL_LUT1_gc
#define EVSYS_CHANNEL1_CCL_LUT1_gc EVSYS_CHANNEL_CCL_LUT1_gc
#define EVSYS_CHANNEL2_CCL_LUT1_gc EVSYS_CHANNEL_CCL_LUT1_gc
#define EVSYS_CHANNEL3_CCL_LUT1_gc EVSYS_CHANNEL_CCL_LUT1_gc
#define EVSYS_CHANNEL4_CCL_LUT1_gc EVSYS_CHANNEL_CCL_LUT1_gc
#define EVSYS_CHANNEL5_CCL_LUT1_gc EVSYS_CHANNEL_CCL_LUT1_gc
#define EVSYS_CHANNEL0_CCL_LUT2_gc EVSYS_CHANNEL_CCL_LUT2_gc
#define EVSYS_CHANNEL1_CCL_LUT2_gc EVSYS_CHANNEL_CCL_LUT2_gc
#define EVSYS_CHANNEL2_CCL_LUT2_gc EVSYS_CHANNEL_CCL_LUT2_gc
#define EVSYS_CHANNEL3_CCL_LUT2_gc EVSYS_CHANNEL_CCL_LUT2_gc
#define EVSYS_CHANNEL4_CCL_LUT2_gc EVSYS_CHANNEL_CCL_LUT2_gc
#define EVSYS_CHANNEL5_CCL_LUT2_gc EVSYS_CHANNEL_CCL_LUT2_gc
#define EVSYS_CHANNEL0_CCL_LUT3_gc EVSYS_CHANNEL_CCL_LUT3_gc
#define EVSYS_CHANNEL1_CCL_LUT3_gc EVSYS_CHANNEL_CCL_LUT3_gc
#define EVSYS_CHANNEL2_CCL_LUT3_gc EVSYS_CHANNEL_CCL_LUT3_gc
#define EVSYS_CHANNEL3_CCL_LUT3_gc EVSYS_CHANNEL_CCL_LUT3_gc
#define EVSYS_CHANNEL4_CCL_LUT3_gc EVSYS_CHANNEL_CCL_LUT3_gc
#define EVSYS_CHANNEL5_CCL_LUT3_gc EVSYS_CHANNEL_CCL_LUT3_gc
#define EVSYS_CHANNEL0_AC0_OUT_gc EVSYS_CHANNEL_AC0_OUT_gc
#define EVSYS_CHANNEL1_AC0_OUT_gc EVSYS_CHANNEL_AC0_OUT_gc
#define EVSYS_CHANNEL2_AC0_OUT_gc EVSYS_CHANNEL_AC0_OUT_gc
#define EVSYS_CHANNEL3_AC0_OUT_gc EVSYS_CHANNEL_AC0_OUT_gc
#define EVSYS_CHANNEL4_AC0_OUT_gc EVSYS_CHANNEL_AC0_OUT_gc
#define EVSYS_CHANNEL5_AC0_OUT_gc EVSYS_CHANNEL_AC0_OUT_gc
#define EVSYS_CHANNEL0_ADC0_WCMP_gc EVSYS_CHANNEL_ADC0_WCMP_gc
#define EVSYS_CHANNEL1_ADC0_WCMP_gc EVSYS_CHANNEL_ADC0_WCMP_gc
#define EVSYS_CHANNEL2_ADC0_WCMP_gc EVSYS_CHANNEL_ADC0_WCMP_gc
#define EVSYS_CHANNEL3_ADC0_WCMP_gc EVSYS_CHANNEL_ADC0_WCMP_gc
#define EVSYS_CHANNEL4_ADC0_WCMP_gc EVSYS_CHANNEL_ADC0_WCMP_gc
#define EVSYS_CHANNEL5_ADC0_WCMP_gc EVSYS_CHANNEL_ADC0_WCMP_gc

#endif
#endif

// end of code